define({
    Layers:[
        {
            "id": "gl_tdzz_hgsdk_py_latest_3_0",
            "caption": "旱改水地块",
            colorfiled:[
                {
                    filed:"jh1",
                    filed2:"sfwc1"
                },
                {
                    filed:"jh2",
                    filed2:"sfwc2"
                },
                {
                    filed:"jh3",
                    filed2:"sfwc3"
                },
                {
                    filed:"jh4",
                    filed2:"sfwc4"
                },
                {
                    filed:"jh5",
                    filed2:"sfwc5"
                },
                {
                    filed:"jh6",
                    filed2:"sfwc6"
                },
                {
                    filed:"jh7",
                    filed2:"sfwc7"
                },
                {
                    filed:"jh8",
                    filed2:"sfwc8"
                },
                {
                    filed:"jh9",
                    filed2:"sfwc9"
                },
                {
                    filed:"jh10",
                    filed2:"sfwc10"
                },
                {
                    filed:"jh11",
                    filed2:"sfwc11"
                },
                {
                    filed:"jh12",
                    filed2:"sfwc12"
                }
            ]
        },
        {
            "id": "gl_tdzz_jsydfkdk_py_latest_3_0",
            "caption": "建设用地复垦地块",
            colorfiled:[
                {
                    filed:"jh1",
                    filed2:"sfwc1"
                },
                {
                    filed:"jh2",
                    filed2:"sfwc2"
                },
                {
                    filed:"jh3",
                    filed2:"sfwc3"
                },
                {
                    filed:"jh4",
                    filed2:"sfwc4"
                },
                {
                    filed:"jh5",
                    filed2:"sfwc5"
                },
                {
                    filed:"jh6",
                    filed2:"sfwc6"
                },
                {
                    filed:"jh7",
                    filed2:"sfwc7"
                },
                {
                    filed:"jh8",
                    filed2:"sfwc8"
                },
                {
                    filed:"jh9",
                    filed2:"sfwc9"
                },
                {
                    filed:"jh10",
                    filed2:"sfwc10"
                },
                {
                    filed:"jh11",
                    filed2:"sfwc11"
                },
                {
                    filed:"jh12",
                    filed2:"sfwc12"
                }
            ]
        },
        {
            "id": "gl_tdzz_tdzhzz_py_latest_3_0",
            "caption": "土地综合整治",
            colorfiled:[
                {
                    filed:"jh1",
                    filed2:"sfwc1"
                },
                {
                    filed:"jh2",
                    filed2:"sfwc2"
                },
                {
                    filed:"jh3",
                    filed2:"sfwc3"
                },
                {
                    filed:"jh4",
                    filed2:"sfwc4"
                },
                {
                    filed:"jh5",
                    filed2:"sfwc5"
                },
                {
                    filed:"jh6",
                    filed2:"sfwc6"
                },
                {
                    filed:"jh7",
                    filed2:"sfwc7"
                },
                {
                    filed:"jh8",
                    filed2:"sfwc8"
                },
                {
                    filed:"jh9",
                    filed2:"sfwc9"
                },
                {
                    filed:"jh10",
                    filed2:"sfwc10"
                },
                {
                    filed:"jh11",
                    filed2:"sfwc11"
                },
                {
                    filed:"jh12",
                    filed2:"sfwc12"
                }
            ]
        }
    ]
})